from __future__ import annotations

import argparse
from pathlib import Path

from .error_taxonomy_report import run_error_taxonomy_for_recommended_models


def _parse_str_list(text: str) -> list[str]:
    items = [token.strip() for token in text.split(",") if token.strip()]
    if not items:
        raise ValueError("Expected at least one item.")
    return items


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate FP/FN taxonomy report for recommended models.")
    parser.add_argument(
        "--input-dir",
        default="/Users/seoki/Desktop/research/outputs/noaa_same_area_pooled_benchmark_61day_2026-03-18_leakfix",
        help="Directory containing <region>_pooled_pairwise.csv files.",
    )
    parser.add_argument("--regions", default="houston,nola,seattle", help="Comma-separated region names.")
    parser.add_argument(
        "--recommendation-csv",
        default="/Users/seoki/Desktop/research/outputs/2026-04-04_all_models_seed_sweep_expanded/all_models_seed_sweep_recommendation.csv",
        help="Recommendation CSV generated by all_models_seed_sweep.",
    )
    parser.add_argument(
        "--run-manifest-csv",
        default="/Users/seoki/Desktop/research/outputs/2026-04-04_all_models_seed_sweep_expanded/all_models_seed_sweep_run_manifest.csv",
        help="Run manifest CSV from seed sweep.",
    )
    parser.add_argument("--output-root", required=True, help="Output directory for taxonomy artifacts.")
    parser.add_argument("--seed", type=int, default=42, help="Seed run to analyze.")
    args = parser.parse_args()

    input_dir = Path(args.input_dir).resolve()
    regions = _parse_str_list(args.regions)
    input_paths = {region: input_dir / f"{region}_pooled_pairwise.csv" for region in regions}

    summary = run_error_taxonomy_for_recommended_models(
        input_paths_by_region=input_paths,
        recommendation_csv_path=args.recommendation_csv,
        run_manifest_csv_path=args.run_manifest_csv,
        output_root=args.output_root,
        seed=int(args.seed),
    )
    print(f"summary_json={summary['summary_json_path']}")
    print(f"summary_md={summary['summary_md_path']}")
    print(f"summary_csv={summary['summary_csv_path']}")
    print(f"taxonomy_csv={summary['taxonomy_csv_path']}")


if __name__ == "__main__":
    main()
